import React, { useState } from 'react';
import { useSelector } from 'react-redux';
import axios from 'axios';
import { useDispatch } from 'react-redux';
import { addEventsToRedux } from '../../ReduxToolkit/Slices/CalendarSlice';

const RepeatModal = ({ isOpen, onClose }) => {
    const calendarEvents = useSelector(state => state.calendar.CalendarEvents);
    const photos = useSelector(state => state.photo.Photos);
    const messages = useSelector(state => state.message.messages);
    const dispatch = useDispatch();

    const [selectedTodos, setSelectedTodos] = useState([]);
    const [selectedAccountabilities, setSelectedAccountabilities] = useState([]);
    const [prompt, setPrompt] = useState("");
    const [loading, setLoading] = useState(false);

    const [additionalInfo] = useState(`

🧠 Important Notes for Gemini:

1️⃣ You will be given two arrays from the frontend: 
   - ✅ "selectedTodos" (contains Todo entries from Live Photos)
   - ✅ "selectedAccountabilities" (contains Accountability entries from Messages)

2️⃣ Your job is to generate a **series of Calendar Events** using the natural language prompt.

3️⃣ Every Calendar Event should follow one of these two formats:

📘 Todo Event Format:
{
  Type: 'Todo',
  SpecificEventId: 'uuid',            ← You (Gemini) can generate this
  title: 'Task Name',
  start: 'ISO8601 format',
  end: 'ISO8601 format',
  timeSlot: 'Readable format',
  CollectionType: 'PhotoCollection',
  fromDb: false,
  TodoId: 'This MUST be taken from selectedTodos array',
  verified: false
}

📗 Accountability Event Format:
{
  Type: 'Accountability',
  SpecificEventId: 'uuid',            ← You (Gemini) can generate this
  title: 'Message',
  start: 'ISO8601 format',
  end: 'ISO8601 format',
  timeSlot: 'Readable format',
  CollectionType: 'MessageCollection',
  fromDb: false,
  AccountabilityId: 'This MUST be taken from selectedAccountabilities array',
  verified: false
}

---

📌 Example Set (Generated from input):

[
  {
    Type: 'Todo',
    SpecificEventId: '449140a3-b085-4280-8b80-06afc7a7d177',
    title: 'vit gym',
    start: '2025-06-27T00:40:00.000Z',
    end: '2025-06-27T01:50:00.000Z',
    timeSlot: '6:10AM - 7:20AM / 27/6/2025',
    CollectionType: 'PhotoCollection',
    fromDb: false,
    TodoId: '86fb57a6-5e21-45c1-a69e-d195a335f63d',
    verified: false
  },
  {
    Type: 'Accountability',
    SpecificEventId: '6845bd3a-4fd5-4f48-bb23-a7ffd18132f7',
    title: 'I am gay',
    start: '2025-06-27T00:40:00.000Z',
    end: '2025-06-27T00:50:00.000Z',
    timeSlot: '6:10AM - 6:20AM / 27/6/2025',
    CollectionType: 'MessageCollection',
    fromDb: false,
    AccountabilityId: 'cbe3daf7-db42-40d7-9d07-bcf6670f6e30',
    verified: false
  },
  {
    Type: 'Accountability',
    SpecificEventId: 'a128e6d9-3fa8-431d-950c-7716f74c3213',
    title: 'I am gay',
    start: '2025-06-27T01:40:00.000Z',
    end: '2025-06-27T01:50:00.000Z',
    timeSlot: '7:10AM - 7:20AM / 27/6/2025',
    CollectionType: 'MessageCollection',
    fromDb: false,
    AccountabilityId: 'cbe3daf7-db42-40d7-9d07-bcf6670f6e30',
    verified: false
  }
]

 Summary:
- "TodoId" must come from the selected photo.
- "AccountabilityId" must come from the selected message.
- "SpecificEventId" can be randomly generated by you.
- Events can be constructed  such that Accountabilities and Todos collide (overlap in time) for validation logic to work
-and the accountabiity event time and todo event time need to colide to it depends on the user

`);



    if (!isOpen) return null;

    const toggleTodo = (photo) => {
        setSelectedTodos(prev =>
            prev.some(p => p.id === photo.id)
                ? prev.filter(p => p.id !== photo.id)
                : [...prev, photo]
        );
    };

    const toggleAccountability = (msg) => {
        setSelectedAccountabilities(prev =>
            prev.some(m => m._id === msg._id)
                ? prev.filter(m => m._id !== msg._id)
                : [...prev, msg]
        );
    };

    const isTodoSelected = (photo) => selectedTodos.some(p => p.id === photo.id);
    const isAccountabilitySelected = (msg) => selectedAccountabilities.some(m => m._id === msg._id);

    const handleGenerate = async () => {
        if (!prompt.trim()) {
            alert(" Prompt cannot be empty.");
            return;
        }

        if (selectedTodos.length === 0 && selectedAccountabilities.length === 0) {
            alert(" Please select at least one Todo or Accountability item.");
            return;
        }

        try {
            setLoading(true);
            const res = await axios.post('http://localhost:3000/apiGenerateEvents/generate-events', {
                selectedTodos,
                selectedAccountabilities,
                prompt,
                additionalInfo
            });

            if (res.status === 200) {
                alert("✅ Events generated successfully!");
                res.data.events.forEach(event => dispatch(addEventsToRedux(event)));

                // You can pass res.data back to parent or use Redux dispatch

            } else {
                alert(" Something went wrong!");
            }

        } catch (err) {
            console.error("Error generating events:", err);
            alert(" Failed to generate events. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black/30 z-50 flex justify-center items-center" onClick={onClose}>
            <div className="bg-white p-6 rounded-xl shadow-xl w-full max-w-5xl" onClick={(e) => e.stopPropagation()}>
                <h2 className="text-xl font-bold mb-4">Repeat Events</h2>
                <div className="grid grid-cols-2 gap-6">

                    {/* Left Column: To-dos */}
                    <div>
                        <h3 className="font-semibold text-gray-700 mb-2">To dos</h3>
                        <div className="flex flex-col h-[50%]  overflow-x-scroll gap-2">
                            {photos.map(photo => (
                                <button
                                    key={photo.id}
                                    onClick={() => toggleTodo(photo)}
                                    className={`px-4 py-2 rounded text-left transition ${isTodoSelected(photo)
                                        ? 'bg-blue-500 text-white'
                                        : 'bg-blue-100 hover:bg-blue-200'
                                        }`}
                                >
                                    {photo.photoName}
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* Right Column: Accountabilities */}
                    <div>
                        <h3 className="font-semibold  text-gray-700 mb-2">Accountabilities</h3>
                        <div className="flex flex-col h-[50%] overflow-x-scroll borde gap-2">
                            {messages.map(msg => (
                                <button
                                    key={msg._id}
                                    onClick={() => toggleAccountability(msg)}
                                    className={`px-4 py-2 rounded text-left transition ${isAccountabilitySelected(msg)
                                        ? 'bg-red-500 text-white'
                                        : 'bg-green-100 hover:bg-green-200'
                                        }`}
                                >
                                    {msg.message}
                                </button>
                            ))}
                        </div>
                    </div>

                </div>

                {/* Prompt Input Field */}
                <div className="mt-6">
                    <label className="block font-medium text-gray-700 mb-1">Repeat Prompt</label>
                    <textarea
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        className="w-full border rounded-lg p-3 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
                        rows={3}
                        placeholder="E.g. Repeat wake-up task at 5AM every weekday for 3 weeks"
                    />
                </div>

                {/* Generate Button */}
                <div className="mt-4 flex justify-end">
                    <button
                        onClick={handleGenerate}
                        disabled={loading}
                        className="bg-indigo-600 text-white px-6 py-2 rounded-lg hover:bg-indigo-700 transition disabled:opacity-50"
                    >
                        {loading ? "Generating..." : "Generate Events"}
                    </button>
                </div>
            </div>
        </div>
    );
};

export default RepeatModal;
